- hosts: [terra-ansible]
  tasks:
  - name: get Python3, virtualenv
    apt:
     pkg:
     - python3
     - virtualenv
     update_cache: yes
    become: true
  - name: Django + Django rest
    pip: 
     virtualenv: /home/ubuntu/venv
     name: 
      - django 
      - djangorestframework

