- hosts: [terra-ansible]
  tasks:
  - name: get Python3, virtualenv
    apt:
     pkg:
     - python3
     - virtualenv
     update_cache: yes
    become: true
 
  - name: Django + Django rest
    pip: 
     virtualenv: /home/ubuntu/venv
     name: 
      - django 
      - djangorestframework
 
  - name: Create project
    shell: '. /home/ubuntu/venvtest/venv/bin/activate; django-admin startproject setup /home/ubuntu/venvtest'
    ignore_errors: true

  - name: Alte hosts 
    lineinfile: 
      path: /home/ubuntu/venvtest/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
